### ISSUE TITLE
alfredToday not working w/ new Alfred

### ISSUE THREAD

**Issue by califa** [jeeftor/alfredToday#11]
Hey, I'm on a new computer and trying to get alfredToday to work.

`tcgc` does nothing, and trying to enable Google results in this:

![image](https://user-images.githubusercontent.com/602352/28284008-7f753f20-6ae4-11e7-9935-915055b590f0.png)

I've deleted & re-added the workflow. I've done `tcreset`. Nothing seems to work.

It might have to do w/ the [Fixum workflow](https://github.com/deanishe/alfred-fixum), which helps Alfred not take up my entire CPU. Here's part of its log file:

```11:39:43 fixum.py:329 INFO     found AW workflow: user.workflow.D64DF670-8430-4506-BB1D-A59343483E47
11:39:43 fixum.py:330 INFO                  name: Alfred Today
11:39:43 fixum.py:331 INFO             bundle ID: org.jeef.today
11:39:43 fixum.py:332 INFO            AW version: 1.21.1
11:39:43 fixum.py:341 INFO     [!!] workflow "Alfred Today" is using outdated version (1.21.1) of Alfred-Workflow
11:39:43 fixum.py:193 INFO         updating "Alfred Today" ...
11:39:43 fixum.py:199 INFO         installed new version of Alfred-Workflow
11:39:43 fixum.py:353 INFO     
11:39:43 fixum.py:373 INFO     [DONE] updated 1 workflow(s) with a newer version of Alfred-Workflow```

Thanks!

**Comment by jeeftor** [comment]
I'll need a few days to get to this most likely. Are you running a local web server or anything? I think the google Auth processes opens up a local server while it's trying to auth the first time if I remember correctly....

**Comment by califa** [comment]
I wasn't at the time. It opened the Google auth screen initially but gave
me a timeout error after I logged in. From that point it wouldn't open the
login screen.

**Comment by jeeftor** [comment]
Did you try the Manual Authorization section of the documentation?  

## Manual Authorization
There are a variety of random reasons why the authorization may not work automatically.  If you are having trouble you can try to manually authorize.

1) First open a terminal window by right clicking on the **Alfred Today** item in your workflow list

![term](https://raw.githubusercontent.com/jeeftor/alfredToday/master/docs/rightClick.png)

2) type `python src/wf_authorize_google.py` in the terminal.  This "should" open a web browser with the option to authorize the application.

If everything works correctly you will see something like this:

```
19:55:06 tools.py:388 INFO
19:55:06 tools.py:389 INFO      ******  AUTHORIZATION SUCCESS  ******
19:55:06 tools.py:390 INFO
```

If there is a problem you will get something like this.

```
19:52:00 tools.py:301 DEBUG    Starting auth function
19:52:00 tools.py:317 INFO
19:52:00 tools.py:318 INFO      ******  AUTH ERROR DETECTED ******
19:52:00 tools.py:319 INFO
19:52:00 tools.py:320 INFO          [Errno 48] Address already in use
19:52:00 tools.py:321 INFO
19:52:00 tools.py:322 INFO      ********* END AUTH ERROR *********
```

If you run into problems open an [issue](https://github.com/jeeftor/alfredToday/issues) and/or post on [alfred forum link](http://www.alfredforum.com/topic/9271-today-view-for-google-calendar-and-microsoft-exchange/?p=46109)


**I guess you probably did do this because you said you got address already in use issue?  Could you maybe try it again just for kicks after a reboot?**

**Comment by califa** [comment]
1. Rebooted
2. Went through your steps

```╰─$ python src/wf_authorize_google.py
11:38:57 wf_authorize_google.py:68 INFO     Running Authorization
No handlers could be found for logger "oauth2client.util"
0:292: execution error: "https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=1038503064347-ccse7mhbrvr0t73mc02m2ihtrsh1gtcl.apps.googleusercontent.com&access_type=offline" doesn’t understand the “open location” message. (-1708)
70:78: execution error: Can’t get application "firefox". (-1728)
```

3. It opened Safari and I logged in with my email, went through 2FA, authorized.

![image](https://user-images.githubusercontent.com/602352/28383763-26cdb386-6c77-11e7-9f07-f39cd9e62613.png)

4. The process didn't shut down after the firefox line or after authorization, and it didn't show anything new (didn't show either of the messages you mentioned)
5. Shut it down.

```Traceback (most recent call last):
  File "src/wf_authorize_google.py", line 90, in <module>
    sys.exit(wf.run(main))
  File "/Users/joel/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D64DF670-8430-4506-BB1D-A59343483E47/src/workflow/workflow.py", line 2236, in run
    func(self)
  File "src/wf_authorize_google.py", line 86, in main
    authorize(wf)
  File "src/wf_authorize_google.py", line 69, in authorize
    g = GoogleInterface(wf)
  File "/Users/joel/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D64DF670-8430-4506-BB1D-A59343483E47/src/GoogleInterface.py", line 49, in __init__
    self._authorize_google()
  File "/Users/joel/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D64DF670-8430-4506-BB1D-A59343483E47/src/GoogleInterface.py", line 73, in _authorize_google
    self.credentials = tools.run_flow_wf(self.wf, flow, self.store, flags, http=self.HTTP_INSTANCE)
  File "/Users/joel/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D64DF670-8430-4506-BB1D-A59343483E47/src/lib/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/joel/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D64DF670-8430-4506-BB1D-A59343483E47/src/lib/oauth2client/tools.py", line 368, in run_flow_wf
    httpd.handle_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 276, in handle_request
    fd_sets = _eintr_retry(select.select, [self], [], [], timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
```
6. Re-ran it. Same thing every time.

**Comment by jeeftor** [comment]
Ok - so this is a little confusing because i'm not an oauth2 master.  

Did you try to navigate to this url: 

https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=1038503064347-ccse7mhbrvr0t73mc02m2ihtrsh1gtcl.apps.googleusercontent.com&access_type=offline

I believe the way things are "supposed" to work is described here: https://developers.google.com/api-client-library/python/guide/aaa_oauth

I pretty much copied the code from Google and nobody has run into issues before ... how motivated are you to work this out?  If very we could try to setup a sample app to see if you can authorize it - i'm assuming you have some funky setting on your system that is stopping the auth flow.

**Comment by jeeftor** [comment]
Ok so I just ran the auth process:

I removed my credentials
`rm ~/.credentials/calendar-alfred-today.json`


Then i ran: `python src/wf_authorize_google.py`

> 
> 08:59:29 wf_authorize_google.py:68 INFO     Running Authorization
> No handlers could be found for logger "oauth2client.util"
> 09:00:02 tools.py:388 INFO
> 09:00:02 tools.py:389 INFO      ******  AUTHORIZATION SUCCESS  ******
> 09:00:02 tools.py:390 INFO
> 09:00:02 GoogleInterface.py:75 INFO     Storing credentials to [/Users/xxxxx/.credentials/calendar-alfred-today.json]
> 09:00:02 workflow.py:2267 ERROR    'NoneType' object has no attribute 'authorize'
> Traceback (most recent call last):
>   File "/Users/xxxxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/src/workflow/workflow.py", line 2260, in run
>     func(self)
>   File "src/wf_authorize_google.py", line 86, in main
>     authorize(wf)
>   File "src/wf_authorize_google.py", line 69, in authorize
>     g = GoogleInterface(wf)
>   File "/Users/xxxx/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/src/GoogleInterface.py", line 51, in __init__
>     http = credentials.authorize(self.HTTP_INSTANCE)
> AttributeError: 'NoneType' object has no attribute 'authorize'

I got a bunch of stupid errors here - but everything DID work correctly ... i'll have to poke around more to try to make sense of things...

**Comment by califa** [comment]
Tried it again with these instructions, but got the same error :(

![image](https://user-images.githubusercontent.com/602352/28475496-5aadafe0-6e01-11e7-8239-d0fd04a3c677.png)

Just checked and opening `localhost:8080` does the same.

**Comment by califa** [comment]
Any ideas? :)

**Comment by jeeftor** [comment]
So the other question is right after a reboot does navigating to `localhost:8080` or `localhost` still give you that Ngnix Error?

Perhaps you already have e a local web server running which is causing issues?

**Comment by califa** [comment]
That was it! I had an instance of nginx running for some reason 🤔 
Found it by running `sudo lsof -i :8080`

Is there a way for me to change alfredToday's port moving forward?

Thanks!

**Comment by jeeftor** [comment]
Um... thats a good question - I'm not sure because the port its using is part of the Google Python API they provide here: https://developers.google.com/google-apps/calendar/quickstart/python feel free to dig around.  I'm pretty sure there IS a way but this is a 1-time deal so hopefully it shouldn't be an issue moving forward.

**Comment by technicalpickles** [comment]
I ran into this too, and had to `brew services stop nginx`, go through the oauth, and then restart nginx.

Port 8080 is pretty common. Maybe could use something a little more random?

**Comment by jeeftor** [comment]
Unfortunately, the port I think is specified by the google auth library - i
don't think i have the option to change it.
