### ISSUE TITLE
Time-zone problem

### ISSUE THREAD

**Issue by resoliwan** [jeeftor/alfredToday#12]
I live in South Korea.
So my time zone is not a US/Eastern
but in the source code 

today.py 58
`
    morning = timezone("US/Eastern").localize(datetime.today().replace(hour=0, minute=0, second=1) + timedelta(days=date_offset))
    night = timezone("US/Eastern").localize(datetime.today().replace(hour=23, minute=59, second=59) + timedelta(days=date_offset))
`

the time-zone is constant.
Could you make it to change the time-zone? 

Thank you!

**Comment by jeeftor** [comment]
I guess that wouldn't be too hard to fix. We could do a user selectable option in the Alfred vars....

**Comment by jeeftor** [comment]
I'll try to get to this this weekend ... seems easy enough fix perchance.

**Comment by jeeftor** [comment]
Did this ever get resolved - I forgot if i actually got to it.

**Comment by califa** [comment]
@jeeftor this is still an issue, and localization actually isn't working as far as I could tell. I have some calendars accidentally still set to EST and others to GMT+3 since I'm working abroad atm. Right now all events are showing up as their set time rather than accounting for time zones.

For instance: `8pm GMT+3` appears before `9pm EST`, But `9pm EST` is actually `2pm GMT+3` and should definitely appear before `8pm`.

The easy fix for me was to change all the timezones in my various calendars, which didn't take that long, but it'd be useful if this happened automatically.

**Comment by resoliwan** [comment]
I have seen that you add a time zone option. 
So I will closed this issuse.
Thanks jeeftor

**Comment by califa** [comment]
I think maybe this is worth reopening if it's not working as intended
