### ISSUE TITLE
Update notification won't go away after update

### ISSUE THREAD

**Issue by hasStephen** [jeeftor/alfredToday#5]
First of all, thank you for this awesome workflow. It really is helpful and I use it every day.

I updated to the most recent version (4.3) of Today, and when I activate it though Alfred 3, it's still telling me there is an update available. Is there a way to remove this or show it that the most current version is installed?

**Comment by jeeftor** [comment]
Well @hasStephen  its not called **today** so that you can use it every other day :)

As far as the update code goes i'm using a library from: (http://www.deanishe.net/alfred-workflow/) that handles the update code.  

I have some ideas:

1) type `dbgtoday workflow:open cache`

That will open the cache folder and there will be a file called:
`__workflow_update_status.cpickle`

You could try to delete this file?

You could try the delete cache option of the workflow debug menu - or you could try `tcreset`

Lastly you could open the logs: `dbgtoday workflow:openlog`  and browse around.  For example my version says:

```
10:45:45 workflow.py:2351 DEBUG    Set last run version : 4.3.1
10:45:45 workflow.py:2194 DEBUG    Workflow finished in 0.019 seconds.
10:45:46 workflow.py:2156 DEBUG    Workflow version : 4.3.1
```

(there is not a 4.3.1 yet btw - its just i have a script that when I upload a new version it auto-increments mine)

Do let me know what you find! and i'm really glad you like the workflow.  I also use it MULTIPLE times a day.  Especially the meeting-joining links part.

**Comment by hasStephen** [comment]
Thank you for the quick reply! `dbgtoday workflow:open cache` then going to `workflow:deletecache` seemed to work like a charm.

**Comment by jeeftor** [comment]
Sweet!
